name = "webdav"
main = "src/index.ts"
compatibility_date = "2023-01-01"

account_id = "b9026a15a586c9fbdd6d8ee2947a8cdb"  # Replace with the desired account_id

[vars]
USERNAME = "afosne"
PASSWORD = "Sunshine08."
BUCKET_NAME = "webdav"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "webdav"
