name: Deploy to Cloudflare Workers

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Create wrangler.toml
        env:
          USERNAME: ${{ secrets.USERNAME || '_user' }}
          PASSWORD: ${{ secrets.PASSWORD || '_pass' }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME || 'bucket' }}
        run: |
          sed -e "s/\$USERNAME/$USERNAME/g" \
              -e "s/\$PASSWORD/$PASSWORD/g" \
              -e "s/\$BUCKET_NAME/$BUCKET_NAME/g" \
              -e "s/\$ACCOUNT_ID/99760fee2f45db1d662092b8e356de5e/g" \
              wrangler.toml.template > wrangler.toml
            cat wrangler.toml

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
