name: Deploy to Cloudflare Workers

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: "nbCzbZqv90RcW6ZlAre5NIQqgopPzs9jyHTMRscg"
